[project]
name = "physsplat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mohamadmsalman82", email = "mohamad.salman@mail.utoronto.ca" }
]
requires-python = ">=3.12"
dependencies = [
    "einops>=0.8.2",
    "fastapi>=0.141.1",
    "h5py>=3.16.0",
    "hdbscan>=0.8.44",
    "imageio>=2.37.4",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "omegaconf>=2.3.1",
    "onnx>=1.22.0",
    "onnxruntime>=1.29.0",
    "onnxscript>=0.7.1",
    "pillow>=12.3.0",
    "pybullet>=3.2.7",
    "rembg>=2.0.83",
    "rerun-sdk>=0.36.3",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.1",
    "torch>=2.13.0",
    "transformers>=5.16.1",
    "trimesh>=5.0.0",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
physsplat = "physsplat:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
